name: Manual Matrix Test

on:
  workflow_dispatch:

jobs:
  changed-files:
    name: Get changes
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      matrix_jq: ${{ steps.set-matrix_jq.outputs.matrix_jq }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # needed for tj-actions/changed-files
      - name: Get changed files
        id: changed-files
        uses: ./
        with:
          json: true
      - name: List all changed files
        run: |
          echo '${{ steps.changed-files.outputs.all_changed_files }}'

      - id: set-matrix
        run: echo "::set-output name=matrix::{\"container\":${{ steps.changed-files.outputs.all_changed_files }}}"

      - id: set-matrix_jq
        run:
          DATA=$(echo ${{ steps.changed-files.outputs.all_changed_files }} | jq -c '. | map(split("/")[0]) | unique')
          echo "matrix_jq=$DATA" >> "$GITHUB_OUTPUT"

  matrix-job:
    name: Run Matrix Job
    runs-on: ubuntu-latest
    needs: [changed-files]
    strategy:
      matrix:
        set-matrix: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
        set-matrix_jq: ${{ fromJSON(needs.changed-files.outputs.matrix_jq) }}
      max-parallel: 4
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: |
          echo ${{ matrix.container }}
